### ISSUE TITLE
Missing character for degrees

### ISSUE THREAD

**Issue by Thundras** [keshikan/DSEG#11]
Hi, first of all thanks for the great fonts. I am about to program an LCD weather display and with the weather font this is perfect, but in the 7 and 14 segment fonts unfortunately the degree sign is missing.

sorry for my bad English

**Comment by keshikan** [comment]
Hi, There is no degree sign(° U+00B0) in DSEG series.
I'll consider adding it with future update.

**Comment by Thundras** [comment]
Thank you for your quick response. I think it would also be helpful for others if there were the degree signs.

**Comment by keshikan** [comment]
Hi, I added degree sign on [v0.46](https://github.com/keshikan/DSEG/releases/tag/v0.46)
Sorry for the delay.
![dseg_degree](https://user-images.githubusercontent.com/16370619/76693300-1324bb00-66a6-11ea-9170-995d22097a8e.png)
