### ISSUE TITLE
Mixed case used in font definition for both the upper case and lower case definitions

### ISSUE THREAD

**Issue by Terhiman** [keshikan/DSEG#12]
Looking at a preview and using DSEG7Classic-BoldItalic.woff2 it is lowercasing uppecase chars and vice versa. Looking at the prview in chrome debugger shows me the attacjed font definitiion. Is the lower case ascii set supposed to be a mirror of the uppercase set and be a combination of both upper and lower case chars?  
![image](https://user-images.githubusercontent.com/27024441/47918545-cb343800-dea4-11e8-8818-113648b3bb6c.png)

**Comment by keshikan** [comment]
Hi.

Yes, in DSEG series, upper and lower case definition is same, and it is a combination of both upper and lower characters.

Please refer to following image.
(quoted from https://www.keshikan.net/fonts-e.html)
![charactercode](https://user-images.githubusercontent.com/16370619/48237476-1bae1700-e40a-11e8-8f10-2e49d6fcf4ee.PNG)
