### ISSUE TITLE
Update NPM package

### ISSUE THREAD

**Issue by fetus-hina** [keshikan/DSEG#13]
I appreciate the wonderful project.

Now it seems that a little old v0.43 is being deployed to npmjs.
Could you update it to v0.45?

**Comment by keshikan** [comment]
Thanks for your comment.
I published [dseg v0.45 packages](https://www.npmjs.com/package/dseg) at npmjs.com .
Please check it out.

**Comment by fetus-hina** [comment]
Great! Thank you for the work!
