### ISSUE TITLE
Decimal numbers using comma character?

### ISSUE THREAD

**Issue by hulinning2** [keshikan/DSEG#17]
Hi, 
I look into the table I could not find any symbol for comma character. So it is not possible to display decimal numbers using comma character instead of a dot.
Is that correct or you have another way to display the comma character?
Ex: In Europe 123, 45  but in US it is 123.45

Thanks

**Comment by keshikan** [comment]
Hi, Thank you for your information.

Comma character is not included in this font.
So please use period character instead.
