### ISSUE TITLE
Small display issue in the font chart on the support page

### ISSUE THREAD

**Issue by brunchboy** [keshikan/DSEG#3]
I noticed that in both the English and Japanese versions of the support page, in the chart in Section 3.5, the Character for U+005C is being displayed incorrectly. Even though it is seems to be a backslash (‘ \ ’) when copied and pasted, and that is what the character looks like in the DSEG samples, for some reason it is displaying as a yen sign (‘ ¥ ’) in the chart?

Thank you for creating these great fonts and sharing them as open-source! I am planning to use DSEG7 in my [beat-link-trigger](https://github.com/brunchboy/beat-link-trigger) application to display times in the style that they appear on CDJ displays, because I am adding the ability to show the waveform of the track that is playing, which will be helpful to people running light shows synchronized with the music, as they can see what is coming up.

**Comment by keshikan** [comment]
Thank you for  information.

I used Japanese font set in CSS by mistake, and I corrected [just now.](http://www.keshikan.net/fonts-e.html)
（cf. In Japan Industrial Standards, Yen mark (‘ ¥ ’) is assigned to  U+005C.）

![test](https://user-images.githubusercontent.com/16370619/27092371-0a0293e2-509e-11e7-96af-870a2a0167ea.png)

And thank you again for using DSEG fonts.

**Comment by brunchboy** [comment]
I figured it must be something like that. How strange that there is an incompatible version of Unicode, which is supposed to be universal for all languages everywhere. But that is what is so great about standards, right? There are so many to choose from! 😉 

The fix looks good, and so does your font! Here is a snapshot of a recent version of the UI that I have been building with it, thanks again for helping it look so polished:
<img width="585" alt="Player Status window as it was on Saturday, June 17" src="https://user-images.githubusercontent.com/2228869/27269369-ea69332e-547b-11e7-933b-e01146fe9b7a.png">
