### ISSUE TITLE
How do you get the "faint" inactive segments look?

### ISSUE THREAD

**Issue by mgrunwald** [keshikan/DSEG#32]
Your font is great, thanks a lot!
Is there a way to get the  "faint" inactive segments look, like in all of your examples?  Or is that something I need to implement manually?

**Comment by keshikan** [comment]
Hi,
Please overlay the black digits on the gray digits manually.
DSEG fonts contain no grayscale color.

**Comment by mgrunwald** [comment]
Thanks!
