### ISSUE TITLE
Add npm package

### ISSUE THREAD

**Issue by nils-werner** [keshikan/DSEG#4]
Nowadays web-people prefer to install dependencies like frameworks, CSS and fonts using npm or yarn.

Can you provide a `package.json` and register a package on npmjs.com so that people can easily reference your font?

**Comment by nils-werner** [comment]
Posted pull request #5

**Comment by keshikan** [comment]
Hi, thank you for pull request.
I'll add your package.json with a little change, and publish on npmjs.com soon.
